### ISSUE TITLE
Rocket Launchers consistently show incorrect accuracy between levels 1 and 6.

### ISSUE THREAD

**Issue by andofantablo** [amvi88/BunkersAndBadasses#15] opened 2024-07-09 15:01 UTC
1. Thank you for the generator! It's really useful :)

2. I've noticed the rocket launchers are off on the accuracy.
Happens across Craft/Randomise/Batch and produces accuracy of 1-5 / 6-10 / 11-15 between levels 1 and 6.

I suspect it might be to do with how the gunStats var is set in GunFactory.cs but I haven't been able to confirm yet - currently setting up my local env and my blazor knowledge is practically none.

![image](https://github.com/amvi88/Bunkers-and-Badasses-Loot-Generator/assets/164227496/9cab0f82-d4b5-492a-9b2b-596034d03ea8)

![image](https://github.com/amvi88/Bunkers-and-Badasses-Loot-Generator/assets/164227496/c47aaadf-99d1-4862-8531-aa84750d2b6e)

Repro steps:
1. open [/gun-randomizer](https://bunkers-and-badasses-app.azurewebsites.net/gun-randomizer)
2. set gun type to "Rocket Launcher"
3. leave level at "1" and press Roll
4. see accuracy incorrect
5. set level to "7" and press Roll
6. see accuracy correct

**Comment by BowTieBloke** [comment] 2024-07-09 15:56
I can confirm the issue, @andofantablo.

This appears to be an error with the ONLINE version only. I just installed the windows version from the installer and it works fine,

Download the release and execute the installer.
https://github.com/amvi88/Bunkers-and-Badasses-Loot-Generator/releases/tag/1.2.0

You can use that version for now.

As the original creator is on a mental health break there will not be a fix for the online version anytime soon.

If there is enough demand I can try and see if I can get this running on my own server, so that we have a version for the future where potential fixes can be deployed. For now, I recommend just using the installer.

**Comment by amvi88** [comment] 2024-07-18 02:47
Interestingly it seems to work for me on the online version, trying all gun generators
![image](https://github.com/user-attachments/assets/beefa53b-cd01-4767-8dfb-99e5060cb7a2)

**Comment by amvi88** [comment] 2024-07-18 02:48
Same in crafting and batch 
![image](https://github.com/user-attachments/assets/06aff27e-50fc-4d96-956b-863a9eb4b084)

**Comment by amvi88** [comment] 2024-07-18 03:13
Please try force loading the page ctrl+f5 i have a hunch that something was cached on your browser because I use web assembly

**Comment by amvi88** [comment] 2024-07-28 22:10
Closed as it was a caching issue due to web assembly

**Closed as completed** 2024-07-28 22:09 UTC
